### ISSUE TITLE
Spreadsheet Suggestions 

### ISSUE THREAD

**Issue by mgrant46** [callysto/curriculum-notebooks#330]
TechnologyStudies/ComputingScience/Courses/spreadsheet-1.ipynb

- [x] We can hyperlink to the Alberta CTS curriculum at the beginning of the notebook. Not sure if you need the list the outcomes at the end. 
- [x] Is there suppose to be hyperlink here? As an alternative to these tasks, you may instead complete the [T4T INF1060 activities].
- [x] Wondering if there is way to make a checklist for each of the tasks? 
- [x] At the the beginning of the course, it says " This course will make use of online spreadsheets such as [Google Sheets](https://sheets.google.com/), [Microsoft Excel](https://www.office.com/) or [EtherCalc](https://ethercalc.net/). Then you will be able to use data from spreadsheets in the next notebook." 

- Microsoft Excel exercises/spreadsheets are not mentioned in the rest of the notebook 

- [x] Method C. Yes is it Callysto Hub.... but I am wondering if we can say also say using a Jupyter Notebook. If so, maybe insert a video what is a Jupyter Notebook https://www.youtube.com/watch?v=SiTSRuSXnUM

**Comment by misterhay** [comment]
I like the idea of including the outcomes at the end, rather than linking to a PDF and having teachers/students scroll to the appropriate page. I'm up for discussing that though.

As to making checklists, I don't think that's possible in a Jupyter Notebook... but someone can correct me if I'm wrong.
