### ISSUE TITLE
Geogebra in Reflections Notebook is Broken

### ISSUE THREAD

**Issue by inygy** [callysto/curriculum-notebooks#64]
#### Description of the Issue
The geogebra cells are frozen.
`<script src="https://cdn.geogebra.org/apps/deployggb.js"></script>` is used to deploy geogebra in the notebook.
The notebook was working when it was origionally committed to master and has been broken sometime since. We need to be careful to maintain backwards compatibility in nbplus so we can avoid breaking notebooks in master.

#### To Reproduce 
"run all cells" in /Mathematics/Reflections/reflections.ipynb in the master branch.

**Comment by ericeasthope** [comment]
I couldn't reproduce frozen cells. Also, I don't see any use of `nbplus` in the notebook.

You might be seeing a race condition, if the GeoGebra applets are attempting to load before `deployggb.js` arrives.

**Comment by ericeasthope** [comment]
@inygy https://github.com/callysto/curriculum-notebooks/commit/7e70e366b7c84d3ac2330b4bba2ee2c10360a0de

I've made the first three GeoGebra plots use RequireJS in a separate cell with the `%%js` magic. It's a temporary solution, but may resolve the instability that you see.

**Comment by sean-fitzpatrick** [comment]
I've come across a GeoGebra behaviour that's not ideal, but maybe tolerable. Whenever you click on an applet, the page jumps (scrolls), which can be disorienting.

On Chrome it's not so bad --  the effect of the jump is to centre the applet you clicked on in the middle of the screen. On Firefox it's much worse: the applet jumps to the very bottom of the screen!

I thought this might be due to having several applets on the screen -- I encountered this with CC-143 -- but I checked a single applet notebook and the same thing happens there.
